### ISSUE TITLE
Analyze upgrading Microsoft.Owin.Security dependency

### ISSUE THREAD

**Issue by rolodato** [auth0/auth0-aspnet-owin#16]
Might fix intermittent issues with `getExternalIdentity` returning `null`.

**Comment by nicosabena** [comment]
This entries at Stack Overflow describe the problem:

http://stackoverflow.com/questions/32928841/issue-with-https-on-production-environment

http://stackoverflow.com/questions/27976507/aspnetapplicationcookie-and-asp-net-sessionid-not-created?rq=1

The issue is with Katana, see https://katanaproject.codeplex.com/workitem/197

There's a fix here: https://github.com/KentorIT/owin-cookie-saver, and also a NuGet package: 
https://www.nuget.org/packages/Kentor.OwinCookieSaver.

**Comment by rkralston** [comment]
I plan on looking more into this next week. Please post something if you find a workaround this weekend.

**Comment by nicosabena** [comment]
Upgrading to the latest Microsoft.Owin and related dependencies (3.0.1) doesn't seem to fix the problem. The simple repro posted [here](https://katanaproject.codeplex.com/workitem/197) continues to fail:

```
public ActionResult Index()
{
    HttpContext.GetOwinContext()
        .Response.Cookies.Append("OwinCookie", "SomeValue");
    HttpContext.Response.Cookies["ASPCookie"].Value = "SomeValue";
    HttpContext.Response.Cookies.Remove("ASPCookie");

    return View();
}
```

**Comment by jerriep** [comment]
@nicosabena Thanks for following up on this. Since upgrading makes no difference, can we close this issue?

**Comment by jerriep** [comment]
Nevermind. I updated to the latest versions in any case because of another issue
