### ISSUE TITLE
Nuget dependency on  "Microsoft.Owin.Host.SystemWeb"

### ISSUE THREAD

**Issue by arieradle** [auth0/auth0-aspnet-owin#38]
The project has reference to Microsoft.Owin.Host.SystemWeb. 
It is referenced and used only by the test project.

This dependency is redundant, please remove it.

**Comment by jerriep** [comment]
Hi @arieradle that reference is indeed required because the `Auth0AccountController` class which is added by the package requires it.

If this is a problem for you I can create a new NuGet package which includes **only** the OWIN middleware and will therefore required less dependencies.

Please let me know if this is required by you.

**Comment by arieradle** [comment]
I would like to have such NuGet.

**Comment by jerriep** [comment]
OK, I will create one for you ;)

**Comment by arieradle** [comment]
10x :smile:

**Comment by jerriep** [comment]
You can use https://www.nuget.org/packages/Auth0-ASPNET-Owin-Libs/ for using just the OWIN middleware
