### ISSUE TITLE
Redirect inside OnTokenExchangeFailed not respected

### ISSUE THREAD

**Issue by IanBuswell-etech** [auth0/auth0-aspnet-owin#59]
Hello,
I have an issue where redirects inside OnTokenExchangeFailed are not respected.

For context:
Currently using Auth0 for authentication only as a phased approach, so have to match up with local records (link via stored auth0 id) to add some claims information to support legacy cookie login which is done on OnAuthenticated.

Example:

```csharp
var provider = new Auth0AuthenticationProvider()
            {
                OnAuthenticated = context =>
                {
                    // Call to local cache/db + claims update work happens here, failure results in an exception
                    throw new Exception("A failure is raised by business code");
                    //return Task.FromResult(0);
                },
                OnTokenExchangeFailed = context =>
                {
                    // Want to go somewhere else, as it's currently legit behaviour in our case
                    context.Response.Redirect("/Home/Failed");
                },
            }
```

However, the resulting url I'm getting redirected to is:
http://localhost:[port]/?error=access_denied

I can see what's causing it within [Auth0AuthenticationHandler.cs](https://github.com/auth0/auth0-aspnet-owin/blob/master/src/Auth0.Owin/Auth0AuthenticationHandler.cs#L310) InvokeReplyPathAsync():
```csharp
if (!context.IsRequestCompleted)
{
    string redirectUri = context.RedirectUri ?? RequestPathBase + Options.RedirectPath.ToString();
    if (context.Identity == null)
    {
    	// add a redirect hint that sign-in failed in some way
    	redirectUri = WebUtilities.AddQueryString(redirectUri, "error", "access_denied");
    }
	
    if (context.Request.Query["state"] != null && context.Request.Query["state"].Contains("ru="))
    {
    	// set returnUrl with state -> ru
        var state = HttpUtilities.ParseQueryString(context.Request.Query["state"]);
        redirectUri = WebUtilities.AddQueryString(redirectUri, "returnUrl", state["ru"]);	
    }
    
    Response.Redirect(redirectUri); 
    context.RequestCompleted();
}
```

Seems as if that url is hardcoded as I cannot access the context.RedirectUri inside any of the relevant action methods, and seemingly always comes through as just  "/" for the initial context.RedirectUri.

Thought ErrorRedirectPath on the Auth0AuthenticationOptions passed in for app.UseAuth0Authentication(options) might work, but that isn't respected in this case either.

Is it possible to force a redirect to a custom url via the OnTokenExchangeFailed delegate?

If not, any suggestions?

**Comment by jerriep** [comment]
@IanBuswell-etech Hmm, yeah I think that particular line you are referring to should honour the `ErrorRedirectPath`. Do you want to redirect to a different path for each request, or is it fine if you set the `ErrorRedirectPath` and we redirect to that path every time?

Also, the `OnTokenExchangeFailed` will only be invoked if an error occurs when the **authorization code** is exchanged for the tokens. In your case, since the authorization failed, an **authorization code** will not be returned and therefore that even will not be invoked.

**BTW**, how do you fail the request from the Auth0 side? Do you have some sort of rule in place?

**Comment by IanBuswell-etech** [comment]
Hello, thanks for responding.

I think just using `ErrorRedirectPath` for every request will be fine for now thanks. I'll not complain if we get the option to set it on each request though.

Think there might be a bit of confusion on the second question. 
We don't fail on Auth0 side, that's successful so we have a token, we're just failing inside the `OnAuthenticated` delegate which is the last thing invoked: [(Auth0AuthenticationHandler.cs Line:130)](https://github.com/auth0/auth0-aspnet-owin/blob/0fa03c054cfd5bc4ce94a4816b9cf074a7dc63dd/src/Auth0.Owin/Auth0AuthenticationHandler.cs#L130).

As it's post the Auth0 request and inside the large try catch statement, the `OnTokenExchangeFailed` is invoked inside the catch [(here)](https://github.com/auth0/auth0-aspnet-owin/blob/0fa03c054cfd5bc4ce94a4816b9cf074a7dc63dd/src/Auth0.Owin/Auth0AuthenticationHandler.cs#L136).

**Comment by jerriep** [comment]
@IanBuswell-etech OK, so I think some of the complications come in because at the point where you "fail" the authentication, the authentication has actually completed successfully. 

The easiest way for you to achieve what you want is to update the `OnAuthenticated` event handler to set the user's `Identity` to null - which means that there is no authenticated user - and then override the `RedirectUri` property of the `AuthenticationProperties` to point to wherever you want to redirect the user.

```
OnAuthenticated = context =>
{
    // Call to local cache/db + claims update work happens here, failure results in an exception
    context.Identity = null;
    context.Properties.RedirectUri = "/wherever";

    return Task.FromResult(0);
},
```

This also gives you complete flexibility to override the redirection URL on a per-request basis.

**Comment by jpercyetech** [comment]
@jerriep Thanks v much - that way seems to be working well for our use case.

**Comment by jerriep** [comment]
@jpercyetech Cool :)

Are you working with @IanBuswell-etech ? If so, can I close this issue?

**Comment by jpercyetech** [comment]
I am, yes.

And yeah go ahead and close - thanks for your help.

**Comment by jerriep** [comment]
Great, thank you!
